### ISSUE TITLE
Does not throw arithmetic overflow errors in release mode.

### ISSUE THREAD

**Issue by jan53n** [Sreyas-Sreelal/malluscript#27]
```terminal
user@home:~/malluscript$ ./target/release/malluscript examples/factorial.ms
Input number:342  
Factoral is : 0
```

**Comment by Sreyas-Sreelal** [comment]
Thank you :)

One way to fix this would be adding 
```Toml
overflow-checks = true
``` 
under `[profile.release]` to let Rust handle the error. But since we are dealing with another language, I think the optimal solution would be adding "checked" arithmetic operation and let malluscript handle it instead.
Like 
```Rust
if let Some(result) = x.checked_mul(y) {
 // process 
} else {
 // throw custom error
}
```
I'll work on it once I get time :)
